apiVersion: apps/v1
kind: Deployment
metadata:
  name: weclouddata
  namespace: weclouddata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weclouddata
  template:
    metadata:
      labels:
        app: weclouddata
    spec:
      containers:
      - name: python-app
        
        image: maxiplux/fastapidevops-auth-sqlite:8fdae4fc658e68d083ee8bd40f62f071149f3903
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 80
