apiVersion: v1
kind: Service
metadata:
  name: weclouddata
  namespace: weclouddata
spec:
  selector:
    app: weclouddata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer